### ISSUE TITLE
some syntax requires a specific python version

### ISSUE THREAD

**Issue by changgoo** [jeonggyukim/pyathena#36]
I've been using some old version of python (3.7 or 3.9). Then, I found that some new additions requires python 3.10 or higher; e.g. https://github.com/jeonggyukim/pyathena/blob/2ee9c8a5e8830086f38e143ebc3a5a7372cbe142/pyathena/core_formation/tools.py#L1300

We might want to add a python version constraint in setup and README.  

In the meantime, I feel that it is too much to load the pyathena package including all submodules. The default module import shouldn't import problem specific submodules.

**Comment by sanghyukmoon** [comment]
> In the meantime, I feel that it is too much to load the pyathena package including all submodules. The default module import shouldn't import problem specific submodules.

I definitely agree with this. Removing the problem specific modules will reduce the import time, and at the same time, do not require additional problem-specific dependencies (which will solve this issue as well, I think). What do you think, @jeonggyukim ?

**Comment by jeonggyukim** [comment]
I agree. I felt that the import time is long sometimes but didn't realized that it is due to loading many submodules. I will create a PR related to this.

**Comment by jeonggyukim** [comment]
I commented out problem-specific import statements, and the loading time is much reduced!
