### ISSUE TITLE
HST file location

### ISSUE THREAD

**Issue by changgoo** [jeonggyukim/pyathena#7]
https://github.com/jeonggyukim/pyathena/blob/c461ac3390d773537ce52393e3ebf68a3282aa46/pyathena/load_sim.py#L694-L695

I don't quite get the naming convention here. Can this be simply something like this?

```
fpkl = osp.join(savdir, '{0:s}.mod.p'.format(osp.basename(cls.files['hst'])))
```

**Comment by jeonggyukim** [comment]
The reason I appended the basename to the `fpkl` is to distinguish between different models that have the same `problem_id`. This is not necessary if the pickled file resides under the base directory. However, one who does not own the base directory may want to have a look at multiple history dumps and pickle them in one directory. For example, if `user2` wants to look at two models

```
/tigress/user1/SF-CLOUD/A
/tigress/user1/SF-CLOUD/B
```
and if they have the same `problem_id` (this is not the case for TIGRESS simulations though), one pickle can overwrite another unless the `savdir` argument for `read_hst()` is different. 

However, I agree that the naming convention is weird and it can be improved a bit. Maybe something like below would be better-looking.

```
fpkl = osp.join(savdir, '{0:s}.{1:s}.mod.p'.format(cls.problem_id, osp.basename(cls.files['hst'])))
```

**Comment by changgoo** [comment]
As long as you have some reasons for this, I won't touch it (I have changed this for my version, so I will revert it back).
