### ISSUE TITLE
Remove rcParams['font.size'] setting in 'plt_hst_zprof.py'

### ISSUE THREAD

**Issue by sanghyukmoon** [jeonggyukim/pyathena#9]
https://github.com/jeonggyukim/pyathena/blob/a7c283258b81fb19a3c9128e0e85ce9aa2432801/pyathena/tigress_dig/plt_hst_zprof.py#L11
This overwrites user's matplotlibrc settings whenever the class `PltHstZprof` is imported. I request to remove this or move it into member functions of `PltHstZprof`.

**Comment by jeonggyukim** [comment]
Thanks for catching this. Fixed.
